name : Keycloak Event listener sns RedFroggy Tag
permissions:
  contents: write
  issues: write
  pull-requests: write

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout required to release
        uses: actions/checkout@v3

      - name: Checkout artifact
        uses: actions/download-artifact@v3
        with:
          name: jar
          path: target

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: setup semantic-release
        run: npm install -g semantic-release @conveyal/maven-semantic-release @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/git @semantic-release/changelog @semantic-release/github

      - name: release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_URL: ${{ github.server_url }}/${{ github.repository }}
        run: semantic-release --prepare @conveyal/maven-semantic-release --publish @semantic-release/github,@conveyal/maven-semantic-release --verify-conditions @semantic-release/github,@conveyal/maven-semantic-release --verify-release @conveyal/maven-semantic-release --use-conveyal-workflow --disable-snapshot-skip-ci --skip-maven-deploy

      - name: Get latest release
        id: latest_release
        uses: kaliber5/action-get-release@v1
        with:
          token: ${{ github.token }}
          latest: true
        run: echo NEW_VERSION=`echo ${{steps.latest_release.outputs.tag_name}} | sed 's/^.//'` >> $GITHUB_OUTPUT
      
      - name: Upload Release sources
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.latest_release.outputs.upload_url }}
          asset_path: ./target/keycloak-event-listener-sns-${{ steps.latest_release.outputs.NEW_VERSION }}-sources.jar
          asset_name: keycloak-event-listener-sns-${{ steps.latest_release.outputs.NEW_VERSION }}-sources.jar
          asset_content_type: jar

      - name: Upload Release javadoc
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.latest_release.outputs.upload_url }}
          asset_path: ./target/keycloak-event-listener-sns-${{ steps.latest_release.outputs.NEW_VERSION }}-javadoc.jar
          asset_name: keycloak-event-listener-sns-${{ steps.latest_release.outputs.NEW_VERSION }}-javadoc.jar
          asset_content_type: jar

      - name: Upload Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.latest_release.outputs.upload_url }}
          asset_path: ./target/keycloak-event-listener-sns-${{ steps.latest_release.outputs.NEW_VERSION }}.jar
          asset_name: keycloak-event-listener-sns-${{ steps.latest_release.outputs.NEW_VERSION }}.jar
          asset_content_type: jar
      
